[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ovos-gguf-embeddings-plugin"
dynamic = ["version"]
description = "A gguf embeddings plugin for OVOS"
readme = "README.md"
license = "Apache-2.0"
authors = [{name = "jarbasai", email = "jarbasai@mailfence.com"}]
requires-python = ">=3.9"
keywords = ["OVOS", "openvoiceos", "plugin", "gguf", "embeddings"]
dependencies = [
    "ovos-plugin-manager>=0.1.0,<3.0.0",
    "numpy",
    "llama-cpp-python",
]

[project.urls]
Homepage = "https://github.com/TigreGotico/ovos-gguf-embeddings-plugin"
Repository = "https://github.com/TigreGotico/ovos-gguf-embeddings-plugin"

[project.optional-dependencies]
test = ["pytest", "numpy"]

[project.entry-points."opm.embeddings.text"]
ovos-gguf-embeddings-plugin = "ovos_gguf_embeddings:GGUFEmbeddings"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["ovos_gguf_embeddings*"]

[tool.setuptools.dynamic]
version = {attr = "ovos_gguf_embeddings.version.__version__"}
